# Generated by Django 5.0.6 on 2024-06-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='original/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('big_thumb', models.ImageField(blank=True, null=True, upload_to='big_thumbs/')),
                ('big_1920', models.ImageField(blank=True, null=True, upload_to='big_1920/')),
                ('d2500', models.ImageField(blank=True, null=True, upload_to='d2500/')),
                ('state', models.CharField(default='pending', max_length=20)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
