# Generated by Django 5.0.6 on 2024-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_big_1920_alter_image_big_thumb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='big_1920',
            field=models.ImageField(blank=True, null=True, upload_to='big_1920s/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='big_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='big_thumbs/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='d2500',
            field=models.ImageField(blank=True, null=True, upload_to='d2500s/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to='originals/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
